### PR TITLE
Clear cached value on terminal event

### LINKED ISSUE #25: Possible issue with certain Observables
An [issue](https://github.com/Polidea/RxAndroidBle/issues/406) appeared with the Bluetooth package `RxAndroidBle` that might be of interest. The authors have deprecated their own `ConnectionSharingAdapter` for sharing BLE connections, and now recommend the use of `RxReplayingShare`. This is my understanding: 

The package has a method `Observable<RxBleConnection> establishConnection( ... )`. This `Observable` is somewhat unusual in that it emits a single item (the connection), and never completes. Unsubscribing from it terminates the connection, and if the connection is lost due to a Bluetooth fault, the subscription is canceled with an `onError()` exception. 

Apparently the issue is that `RxReplayingShare` will continue to emit the "stale" cached connection to subscribers even after the original connection is broken. According to the OP, the problem is that `ReplayingShare` does not react to finalizations. He describes a fix that might be worth considering. Comments appreciated.

### PR DESCRIPTION
**Pull request by JakeWharton**
Closes #25.

### CODE REVIEW

File: replaying-share/src/test/java/com/jakewharton/rx/ReplayingShareObservableTest.java [hunk 1]
```diff
@@ -190,4 +192,57 @@
...
+  }
+
+  @Test public void errorClearsCacheAndResubscribes() {
+    List<String> start = new ArrayList<>();
+    start.add("initA");
+
+    PublishSubject<String> upstream = PublishSubject.create();
+    Observable<String> replayed = upstream.startWith(start).compose(ReplayingShare.<String>instance());
+
+    TestObserver<String> observer1 = new TestObserver<>();
```
Comment (PaulWoitaschek) [inline replaying-share/src/test/java/com/jakewharton/rx/ReplayingShareObservableTest.java]: You can do replayed.test() instead of manually creating the TestObserver and subscribing to it.

Comment (JakeWharton) [reply replaying-share/src/test/java/com/jakewharton/rx/ReplayingShareObservableTest.java]: Yes but then I would have to change all of the tests which I didn't want to bother with. Feel free to send a PR.
